### ISSUE TITLE
undefined symbol: Tss2_MU_TPML_TAGGED_POLICY_Unmarshal

### ISSUE THREAD

**Issue by nm17** [joholl/tpm2-gui#5]
tpm2-tss is on commit 37c5bb566cf2016c49b6ab1305161ae108dbc912, what should I do?

```
Traceback (most recent call last):
  File "/home/nm17/.local/bin/./tpm2_gui", line 5, in <module>
    from tpm2_gui import main
  File "/home/nm17/.local/lib/python3.9/site-packages/tpm2_gui/__init__.py", line 17, in <module>
    from .tpm.tpm import TPM
  File "/home/nm17/.local/lib/python3.9/site-packages/tpm2_gui/tpm/tpm.py", line 14, in <module>
    from tpm2_pytss.binding import (
  File "/home/nm17/.local/lib/python3.9/site-packages/tpm2_pytss/__init__.py", line 1, in <module>
    from .ESAPI import ESAPI
  File "/home/nm17/.local/lib/python3.9/site-packages/tpm2_pytss/ESAPI.py", line 5, in <module>
    from ._libtpm2_pytss import lib
ImportError: /home/nm17/.local/lib/python3.9/site-packages/tpm2_pytss/_libtpm2_pytss.abi3.so: undefined symbol: Tss2_MU_TPML_TAGGED_POLICY_Unmarshal
```

**Comment by joholl** [comment]
Sorry, this project is halted temporarily because tpm2-software/tpm2-pytss is currently re-written.
The majority of this project will be rewritten as well. Thank you for your understanding.
